spring:
  profiles:
    active: main,db
  messages:
    encoding: UTF-8
  redis:
      host: 127.0.0.1
      port: 6379
      # 密码 没有则可以不填
      password:
      # 如果使用的jedis 则将lettuce改成jedis即可
      lettuce:
        pool:
          # 最大活跃链接数 默认8
          max-active: 8
          # 最大空闲连接数 默认8
          max-idle: 8
          # 最小空闲连接数 默认0
          min-idle: 0
#session cache config
shiro:
  redis:
    sessionLive: 30
    sessionPrefix: shiro_redis_session_
    cacheLive: 30
    cachePrefix: shiro_redis_cache_
server:
  port: 8080
  servlet:
      context-path: /main
